/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthFormLayoutRouteImport } from './routes/auth/_formLayout'
import { Route as AuthedLayoutRouteImport } from './routes/_authed/_layout'
import { Route as AuthedLayoutIndexRouteImport } from './routes/_authed/_layout/index'
import { Route as AuthFormLayoutSignUpRouteImport } from './routes/auth/_formLayout/sign-up'
import { Route as AuthFormLayoutSignInRouteImport } from './routes/auth/_formLayout/sign-in'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFormLayoutRoute = AuthFormLayoutRouteImport.update({
  id: '/auth/_formLayout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLayoutRoute = AuthedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLayoutIndexRoute = AuthedLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedLayoutRoute,
} as any)
const AuthFormLayoutSignUpRoute = AuthFormLayoutSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthFormLayoutRoute,
} as any)
const AuthFormLayoutSignInRoute = AuthFormLayoutSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthFormLayoutRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedLayoutIndexRoute
  '/auth': typeof AuthFormLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/auth/sign-in': typeof AuthFormLayoutSignInRoute
  '/auth/sign-up': typeof AuthFormLayoutSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedLayoutIndexRoute
  '/auth': typeof AuthFormLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/auth/sign-in': typeof AuthFormLayoutSignInRoute
  '/auth/sign-up': typeof AuthFormLayoutSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/_layout': typeof AuthedLayoutRouteWithChildren
  '/auth/_formLayout': typeof AuthFormLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/auth/_formLayout/sign-in': typeof AuthFormLayoutSignInRoute
  '/auth/_formLayout/sign-up': typeof AuthFormLayoutSignUpRoute
  '/_authed/_layout/': typeof AuthedLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/_layout'
    | '/auth/_formLayout'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/auth/_formLayout/sign-in'
    | '/auth/_formLayout/sign-up'
    | '/_authed/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthFormLayoutRoute: typeof AuthFormLayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_formLayout': {
      id: '/auth/_formLayout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthFormLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_layout': {
      id: '/_authed/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedLayoutRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_layout/': {
      id: '/_authed/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedLayoutIndexRouteImport
      parentRoute: typeof AuthedLayoutRoute
    }
    '/auth/_formLayout/sign-up': {
      id: '/auth/_formLayout/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthFormLayoutSignUpRouteImport
      parentRoute: typeof AuthFormLayoutRoute
    }
    '/auth/_formLayout/sign-in': {
      id: '/auth/_formLayout/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthFormLayoutSignInRouteImport
      parentRoute: typeof AuthFormLayoutRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedLayoutRouteChildren {
  AuthedLayoutIndexRoute: typeof AuthedLayoutIndexRoute
}

const AuthedLayoutRouteChildren: AuthedLayoutRouteChildren = {
  AuthedLayoutIndexRoute: AuthedLayoutIndexRoute,
}

const AuthedLayoutRouteWithChildren = AuthedLayoutRoute._addFileChildren(
  AuthedLayoutRouteChildren,
)

interface AuthedRouteChildren {
  AuthedLayoutRoute: typeof AuthedLayoutRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedLayoutRoute: AuthedLayoutRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AuthFormLayoutRouteChildren {
  AuthFormLayoutSignInRoute: typeof AuthFormLayoutSignInRoute
  AuthFormLayoutSignUpRoute: typeof AuthFormLayoutSignUpRoute
}

const AuthFormLayoutRouteChildren: AuthFormLayoutRouteChildren = {
  AuthFormLayoutSignInRoute: AuthFormLayoutSignInRoute,
  AuthFormLayoutSignUpRoute: AuthFormLayoutSignUpRoute,
}

const AuthFormLayoutRouteWithChildren = AuthFormLayoutRoute._addFileChildren(
  AuthFormLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AuthFormLayoutRoute: AuthFormLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
